### ISSUE TITLE
Difficulty getting LIV to recognize on Auto

### ISSUE THREAD

**Issue by RoY7x** [LIV/BoneworksLIV#6]
I have been trying to tinker with this for a while tonight, seeing that this was new on modman. I followed the instructions and launched Boneworks first, but the LIV app never seems to recognize this on Auto mode. I'm unsure if I'm somehow missing a step or finding a bug. The only other mods I have loaded on Boneworks are [Entanglement](https://boneworks.thunderstore.io/package/Entanglement/Entanglement/0.3.0/) and [Camera's Plus](https://boneworks.thunderstore.io/package/L4rs/CameraPlus/5.0.1/) since I'm just making sure that it can run smoothly before putting anything else on here.

<img width="914" alt="Screenshot 2022-06-25 011847" src="https://user-images.githubusercontent.com/24259781/175761303-19503ae3-c28b-4394-857a-004a38b61669.png">
<img width="1280" alt="Screenshot 2022-06-25 012111" src="https://user-images.githubusercontent.com/24259781/175761305-88e094da-d83e-4757-a444-bc726792e43f.png">

**Comment by Raicuparta** [comment]
Thanks for reporting this. The Boneworks auto-detection isn't available in the stable branch of LIV, you need to select the "latest" branch in the Steam beta seletion menu. Right click LIV on Steam and go to "Properties" to select this:
![image](https://user-images.githubusercontent.com/3955124/175768590-fc0a6411-dbfe-4f0b-85dd-5a7c4aeafda2.png)

**Comment by RoY7x** [comment]
Thank you for the quick reply!
